### ISSUE TITLE
Move the plugin installation properties from sign to setup action

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notation-action#55]
The [sign action](https://github.com/notaryproject/notation-action?tab=readme-ov-file#notation-sign) requires users to input notation plugin installation properties. As a user, I would expect the plugin installation can be configured and completed in the [setup action](https://github.com/notaryproject/notation-action?tab=readme-ov-file#notation-setup). 

It would be much efficient and flexible if users sign a image multiple times using a Notation Sign action, without specifying the plugin installation each time. 

In addition, if users have multiple plugins, they just need to specify which plugin to use in signing, without installing the plugin per running sign action.

Is it possible to move the plugin installation properties from sign action to setup action?

**Notation Setup**

```
- name: setup Notation CLI
  uses: notaryproject/notation-action/setup@v1
  with:
    version: <version_of_official_Notation_CLI_release>
    url: <url_of_customized_Notation_CLI>
    checksum: <SHA256_of_the_customized_Notation_CLI>
    plugin_name: <notation_signing_plugin_name>
    plugin_url: <plugin_download_url>
    plugin_checksum: <SHA256_of_the_signing_plugin>
```

**Notation Sign**

```
- name: sign releasd artifact with signing plugin
  uses: notaryproject/notation-action/sign@v1
  with:
    plugin: <which_plugin_to_use>
    key_id: <key_identifier_to_sign>
    target_artifact_reference: <target_artifact_reference_in_remote_registry>
    signature_format: <signature_envelope_format>
    plugin_config: <list_of_plugin_defined_configs>
    allow_referrers_api: <boolean_flag_for_referrers_api>
```
